RENDER_HELPER = 0.01;

BASE_SIZE = 49;
BASE_SIZE_REDUCTION = 0.5;
BASE_HEIGHT = 36.25;

WALL_THICKNESS = 1.4;
WALL_CORNER_ROUNDING_RADIUS_OUTER = 4;
WALL_CORNER_ROUNDING_RADIUS_INNER = 2;

FOOT_HEIGHT = 1.8;
FOOT_TOLERANCE = 0.8;
FOOT_TO_WALL_SIZE = WALL_THICKNESS + FOOT_TOLERANCE - BASE_SIZE_REDUCTION;
FOOT_TO_WALL_XY_SIZE = FOOT_TO_WALL_SIZE;
FOOT_TO_WALL_Z_SIZE = FOOT_TO_WALL_SIZE;
FOOT_CORNER_ROUNDING_RADIUS = 4;
FLOOR_THICKNESS = WALL_THICKNESS;
FOOT_CHAMFER_SIZE = 0;

DISPLAY_ROUNDING_RADIUS = 2;
DISPLAY_DEPTH = 6;
DISPLAY_HEIGHT = 15;
DISPLAY_Z_INSET = FOOT_HEIGHT + FOOT_TO_WALL_Z_SIZE + 0.5;
DISPLAY_SPACING = 2;

GRID_FLOOR_THICKNESS = 0.8;
GRID_WALL_HEIGHT = FOOT_HEIGHT;
GRID_WALL_TOLERANCE = 0.5;
GRID_HOLE_SIZE = 40;
GRID_HOLE_ROUNDING_RADIUS = 5;

SPACER_CUTOUT_MIN_WIDTH = 4;
SPACER_ROUNDING_RADIUS = SPACER_CUTOUT_MIN_WIDTH / 2;

IKEA_ALEX_DRAWER_SPACER_HEIGHT = GRID_FLOOR_THICKNESS + GRID_WALL_HEIGHT;
IKEA_ALEX_DRAWER_SPACER_WIDTH = 32.8;
IKEA_ALEX_DRAWER_SPACER_LENGTH = 294;
IKEA_ALEX_DRAWER_SPACER_NR_CUTOUTS = 4;
IKEA_ALEX_DRAWER_SPACER_CUTOUT_SPACING = 5;
IKEA_ALEX_DRAWER_SPACER_CUTOUT_ROUNDING_RADIUS = 5;
