BASE_SIZE = 49;
BASE_HEIGHT = 33.75;
FOOT_HEIGHT = 2;
FOOT_TO_WALL_SIZE = 1.5;

WALL_THICKNESS = 1.4;
FLOOR_THICKNESS = WALL_THICKNESS;

WALL_CORNER_ROUNDING_RADIUS = 2;

FOOT_CORNER_ROUNDING_RADIUS = 1;

DISPLAY_ROUNDING_RADIUS = 2;
DISPLAY_DEPTH = 9;
DISPLAY_HEIGHT = 17;
DISPLAY_Z_INSET = FOOT_HEIGHT + FOOT_TO_WALL_SIZE + 1;